// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5crBPPHOmjHiWanQOHYi0ttng4CBaxrI',
    appId: '1:478703211925:web:5e35dffbfe5c6132c1929c',
    messagingSenderId: '478703211925',
    projectId: 'eventpass-app-e99a0',
    authDomain: 'eventpass-app-e99a0.firebaseapp.com',
    storageBucket: 'eventpass-app-e99a0.firebasestorage.app',
    measurementId: 'G-VXNC7T7SXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlTKY35G2MAc9nEgrqKBkRHVncz7QPQXc',
    appId: '1:478703211925:android:8af057bc9f921a64c1929c',
    messagingSenderId: '478703211925',
    projectId: 'eventpass-app-e99a0',
    storageBucket: 'eventpass-app-e99a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_yTf4R-Y3nJQRnygQDFLMWCbpeHA5uWw',
    appId: '1:478703211925:ios:8bfee3483a244fb1c1929c',
    messagingSenderId: '478703211925',
    projectId: 'eventpass-app-e99a0',
    storageBucket: 'eventpass-app-e99a0.firebasestorage.app',
    iosBundleId: 'com.example.ticketsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_yTf4R-Y3nJQRnygQDFLMWCbpeHA5uWw',
    appId: '1:478703211925:ios:8bfee3483a244fb1c1929c',
    messagingSenderId: '478703211925',
    projectId: 'eventpass-app-e99a0',
    storageBucket: 'eventpass-app-e99a0.firebasestorage.app',
    iosBundleId: 'com.example.ticketsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5crBPPHOmjHiWanQOHYi0ttng4CBaxrI',
    appId: '1:478703211925:web:e8bc078ab9e286c0c1929c',
    messagingSenderId: '478703211925',
    projectId: 'eventpass-app-e99a0',
    authDomain: 'eventpass-app-e99a0.firebaseapp.com',
    storageBucket: 'eventpass-app-e99a0.firebasestorage.app',
    measurementId: 'G-6LLH227YTC',
  );
}
